---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: codeServer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD=123456789
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password 123456789Kk
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /mnt/ssd/media/config/codeServer:/config
    ports:
      - 8103:8443
    restart: unless-stopped