services:
   jdownloader:
    image: jlesage/jdownloader-2:latest
    container_name: jdownloader
    restart: always
  #  user: 1000:1000
    volumes:
        - /mnt/ssd/media/config/jdownloder:/config:rw
        - /mnt/ssd/media/download/Jdownloads:/output:rw
        - /mnt/ssd/media/tv:/data/tv
        - /mnt/ssd/media/tv-opa:/data/tv-opa
        - /mnt/ssd/media/movie:/data/movie
        - /mnt/ssd/media/music:/data/music
        - /mnt/ssd/media/movie-opa:/data/movie-opa
        #- /mnt/ssd/media/logs/config_jdownl:/opt/JDownloader/app/logs #optional
    environment: 
      MYJDOWNLOADER_EMAIL: ahhdqdkanquasndfdc@tmmwj.net #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
      MYJDOWNLOADER_PASSWORD: 1234567 #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
      MYJDOWNLOADER_DEVICE_NAME: raspberrypi #optional
      WEB_LISTENING_PORT: 5800
      #JDOWNLOADER_HEADLESS: 0
      DARK_MODE: 1
      #XDG_DOWNLOAD_DIR: /opt/JDownloader/Downloads/xdg #optional
    ports:
        - 3129:3129 
        - 5800:5800 
