---
version: "2.1"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /mnt/ssd/media/config/HEIMDALL:/config
    ports:
      - 8100:80
    restart: unless-stopped