version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8101:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: '123456789'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - '/mnt/ssd/media/config/PiHole/DNS:/etc/dnsmasq.d'
    restart: unless-stopped