version: '2'
services:    
    browser-chrome:
        hostname: browser-chrome
        image: seleniarm/standalone-chromium:4.0.0-20211213
        environment:
            - VNC_NO_PASSWORD=1
            - SCREEN_WIDTH=1920
            - SCREEN_HEIGHT=1080
            - SCREEN_DEPTH=24
        volumes:
            # Workaround to avoid the browser crashing inside a docker container
            # See https://github.com/SeleniumHQ/docker-selenium#quick-start
            - /dev/shm:/dev/shm
        ports:
          - 4444:4444
        restart: unless-stopped
        
 
volumes:
  dev-data: