version: '3.3'
services:
    deemix: 
        image: registry.gitlab.com/bockiii/deemix-docker:latest
        container_name: Deemix
        volumes:
            - /mnt/ssd/media/download/Musik:/downloads
            - /mnt/ssd/media/config/deemix:/config
        environment:
            - PUID=1000
            - PGID=1000
            - UMASK_SET=022
            - DEEMIX_SINGLE_USER=true
        ports:
            - 6595:6595
        restart: unless-stopped